import { CSPostHogProvider } from "@/lib/posthog";
import Header from "./components/Navbar/Header";
import "./styles/globals.css";
export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <Header />
        <CSPostHogProvider>{children}</CSPostHogProvider>
      </body>
    </html>
  );
}
